# Generated by Django 4.1.7 on 2023-03-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_date_remove_review_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
